name: Build Documentation
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install poetry
        run: |
          python -m pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Build and publish documentation
        run: mkdocs gh-deploy --force
