name: Library test

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    environment: development
    env: 
      API_TOKEN: ${{ secrets.API_TOKEN }}
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_ID: ${{ secrets.APP_ID }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pipenv & dependecies
        run: |
          python -m pip install pipenv
          pipenv install -d
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install library
        run: |
          python -m pip install ./
      - name: Test with pytest
        run: |
          pytest
